
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: internetshopdb
      
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: dockerFile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DATASOURCE_HOST}:3306/internetshopdb
      SPRING_DATASOURCE_USERNAME: ${MYSQL_NAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SECURITY_JWT_SECRET-KEY: ${JWT_SECRET}
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerFile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
